---
title: "visualization_2"
author: "Jiayi Shen"
date: "10/02/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("thomasp85/patchwork")
library(tidyverse)
library(ggridges)
library(patchwork)

#setting up the output format of graphs
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#theme_set(theme_bw() + theme(legend.position = "bottom"))
```


```{r load weather_df}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


# Start a plot

first scatterplot!!
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temp plot",
    x = "min daily temp (C)",
    y = "max daily temp (C)",
    caption = "Data from the rnoaa package"
  )

# x axis is going to be labeled as the variable name by default.
```

